apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f sqlight.docker-compose.yaml -o sqlight-kompose/
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ghost
  name: ghost
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 2424
  selector:
    io.kompose.service: ghost
status:
  loadBalancer: {}
